CreateMon           = 0x0803DA54 |1;
CalculateMonStats   = 0x0803E47C |1;
GetMonData          = 0x0803FBE8 |1;
SetMonData          = 0x0804037C |1;

SetInGameTradeMail  = 0x08053CD4 |1;
ItemIsMail          = 0x080980F8 |1;

memcpy              = 0x081E5E78 |1;

/* -------------------------------------------------------------------------- */

gTradeMail          = 0x02031CCC;
gEnemyParty         = 0x0202402C;
gPlayerParty        = 0x02024284;

gBattleMovesPtr     = 0x080001CC;
